name: Deploy Dev

on:
    push:
        branches:
            - master

    workflow_dispatch:

jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/${{ secrets.USERNAME }}/web/wotstat/dev/ModNotification
                      git pull
                      npm i
                      pm2 start pm2/dev.json
                      pm2 save
